export enum Errores{
ERROR_CURP='LA CURP NO TIENE UN FORMATO VALIDO',
ERROR_CICLO='EL CILO INGRESADO NO ES VALIDO',
ERROR_NIVEL='EL NIVEL INGRESADO NO ES VALIDO',
ERROR_PLAN_ESTUDIO='EL PLAN ESTUDIO INGRESADO NO ES VALIDO',
ERROR_CAMPO_FALTANTE=' ES REQUERIDO',
ERROR_RANGO_CALIFICACIONES='LAS CALIFICACIONES DEBEN DE SER ENTRE (1 Y 10)',
ERROR_LONGITUD_CENTRO_TRABAJO='EL CENTRO DE TRABAJO INGRESADO NO ES  VALIDO',
}